
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jenna
 */
public class EditJFrame extends javax.swing.JFrame {

    private MyHashTable theHT;

    /**
     * Creates new form EditJFrame
     */
    public EditJFrame() {
        initComponents();
        ftePanel.setVisible(false);
        ptePanel.setVisible(false);
        msg.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
    }
    
    public void setHT(MyHashTable theRefVal) {
        theHT = theRefVal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addTab = new javax.swing.JPanel();
        empNumField = new javax.swing.JTextField();
        fNField = new javax.swing.JTextField();
        lNField = new javax.swing.JTextField();
        locField = new javax.swing.JComboBox<>();
        gField = new javax.swing.JTextField();
        fteButton = new javax.swing.JRadioButton();
        pteButton = new javax.swing.JRadioButton();
        deducField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        uploadButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        fNText = new javax.swing.JLabel();
        lNText = new javax.swing.JLabel();
        empNumText = new javax.swing.JLabel();
        locText = new javax.swing.JLabel();
        gText = new javax.swing.JLabel();
        deducText = new javax.swing.JLabel();
        pfpText = new javax.swing.JLabel();
        ftePanel = new javax.swing.JPanel();
        yearlyField = new javax.swing.JTextField();
        yearlyText = new javax.swing.JLabel();
        fteArrow = new javax.swing.JLabel();
        ptePanel = new javax.swing.JPanel();
        hourlyText = new javax.swing.JLabel();
        hrsWeekText = new javax.swing.JLabel();
        wYrText = new javax.swing.JLabel();
        wYrField = new javax.swing.JTextField();
        hourlyField = new javax.swing.JTextField();
        hoursWeekField = new javax.swing.JTextField();
        pteArrow = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        removeTab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        addTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addTabMousePressed(evt);
            }
        });

        locField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(fteButton);
        fteButton.setText("Full Time");
        fteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fteButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(pteButton);
        pteButton.setText("Part Time");
        pteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pteButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        uploadButton.setText("UPLOAD");

        addButton.setText("ADD EMPLOYEE");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        fNText.setText("First Name:");

        lNText.setText("Last Name:");

        empNumText.setText("Employee Number:");

        locText.setText("Location:");

        gText.setText("Gender:");

        deducText.setText("Deduction Rate:");

        pfpText.setText("Profile Picture:");

        yearlyText.setText("Yearly Salary:");

        fteArrow.setText(">");

        javax.swing.GroupLayout ftePanelLayout = new javax.swing.GroupLayout(ftePanel);
        ftePanel.setLayout(ftePanelLayout);
        ftePanelLayout.setHorizontalGroup(
            ftePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ftePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fteArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearlyText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlyField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        ftePanelLayout.setVerticalGroup(
            ftePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ftePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fteArrow)
                .addComponent(yearlyText)
                .addComponent(yearlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hourlyText.setText("Hourly Wage:");

        hrsWeekText.setText("Hrs/W:");

        wYrText.setText("W/Yr:");

        pteArrow.setText(">");

        javax.swing.GroupLayout ptePanelLayout = new javax.swing.GroupLayout(ptePanel);
        ptePanel.setLayout(ptePanelLayout);
        ptePanelLayout.setHorizontalGroup(
            ptePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pteArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hourlyText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(hrsWeekText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoursWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wYrText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wYrField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ptePanelLayout.setVerticalGroup(
            ptePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ptePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hourlyText)
                .addComponent(hourlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hrsWeekText)
                .addComponent(hoursWeekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(wYrText)
                .addComponent(wYrField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pteArrow))
        );

        msg.setForeground(new java.awt.Color(255, 0, 0));
        msg.setText("______________________________________________________");
        msg.setToolTipText("");

        javax.swing.GroupLayout addTabLayout = new javax.swing.GroupLayout(addTab);
        addTab.setLayout(addTabLayout);
        addTabLayout.setHorizontalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addTabLayout.createSequentialGroup()
                                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addTabLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pfpText)))
                                    .addGroup(addTabLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(uploadButton)))
                                .addGap(43, 43, 43)
                                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(addTabLayout.createSequentialGroup()
                                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gText)
                                            .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(deducText)
                                            .addComponent(deducField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(addTabLayout.createSequentialGroup()
                                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fNField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fNText))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lNText)
                                                .addComponent(lNField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(addTabLayout.createSequentialGroup()
                                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(empNumText)
                                                .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(locText)
                                                .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE)))))
                            .addGroup(addTabLayout.createSequentialGroup()
                                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pteButton)
                                    .addComponent(fteButton))
                                .addGap(18, 18, 18)
                                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ftePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ptePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addComponent(msg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        addTabLayout.setVerticalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNText)
                    .addComponent(lNText)
                    .addComponent(pfpText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(uploadButton))
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empNumText)
                            .addComponent(locText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gText)
                            .addComponent(deducText))
                        .addGap(5, 5, 5)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deducField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addComponent(fteButton)
                        .addGap(7, 7, 7)
                        .addComponent(pteButton))
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addComponent(ftePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ptePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(msg))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD", addTab);

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("EDIT", editTab);

        javax.swing.GroupLayout removeTabLayout = new javax.swing.GroupLayout(removeTab);
        removeTab.setLayout(removeTabLayout);
        removeTabLayout.setHorizontalGroup(
            removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        removeTabLayout.setVerticalGroup(
            removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("REMOVE", removeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearAddFields() {
        empNumField.setText(null);
        fNField.setText(null);
        lNField.setText(null);
        gField.setText(null);
        locField.setSelectedIndex(0);
        deducField.setText(null);
        yearlyField.setText(null);
        hoursWeekField.setText(null);
        hourlyField.setText(null);
        wYrField.setText(null);
        buttonGroup1.clearSelection();
        ftePanel.setVisible(false);
        ptePanel.setVisible(false);
    }
    
    private boolean checkEmpInfo(boolean correctFields, String strEN, String fN, String lN, String g, String strDeduc) {
        if (strEN.isEmpty()) {
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                int eN = Integer.parseInt(strEN);
                if (eN < 1) {
                    msg.setText("Employee number must be a positive integer!");
                    msg.setVisible(true);
                    correctFields = false;
                } else if (theHT.searchEmployee(eN) != null){
                    msg.setText("Employee number is already in use!");
                    msg.setVisible(true);
                    correctFields = false;
                }
            } catch(Exception e) {
                msg.setText("Employee number must be a positive integer!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        if (fN.isEmpty()) {
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        }
        if (lN.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        }
        if (g.isEmpty()) {
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        }
        if (strDeduc.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                double deduc = Double.parseDouble(strDeduc);
                if (deduc > 1 || deduc < 0) {
                    msg.setText("Dedcution rate must be a decimal from 0 - 1!");
                    msg.setVisible(true);
                    correctFields = false;
                }             
            } catch (Exception e) {
                msg.setText("Dedcution rate must be a decimal from 0 - 1!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        return correctFields;
    }
    
    private boolean checkFTE(boolean correctFields, String strSalary) {
        if (strSalary.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                double salary = Double.parseDouble(strSalary);
                if (salary <= 0) {
                    msg.setText("Salary must be a positive integer!");
                    msg.setVisible(true);
                    correctFields = false;
                }
            } catch(Exception e) {
                msg.setText("Salary must be a positive integer!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        return correctFields;
    }
    
    private boolean checkPTE(boolean correctFields, String strHourly, String strHPW, String strWPY) {
        if (strHourly.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                double hourly = Double.parseDouble(strHourly);
                if (hourly <= 0) {
                    msg.setText("Hourly wage must be a positive integer!");
                    msg.setVisible(true);
                    correctFields = false;
                }
            } catch(Exception e) {
                msg.setText("Hourly wage must be a positive integer!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        if (strHPW.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                double hPW = Double.parseDouble(strHPW);
                if (hPW < 0 || hPW > 168) {
                    msg.setText("Hours per week must be between 0 and 168 hours!");
                    msg.setVisible(true);
                    correctFields = false;
                }
            } catch(Exception e) {
                msg.setText("Hours per week must be between 0 and 168 hours!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        if (strWPY.isEmpty()){
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
            correctFields = false;
        } else {
            try {
                int wPY = Integer.parseInt(strWPY);
                if (wPY < 0 || wPY > 53) {
                    msg.setText("Weeks per year must be an integer between 0 and 53!");
                    msg.setVisible(true);
                    correctFields = false;
                }
            } catch(Exception e) {
                msg.setText("Weeks per year must be an integer between 0 and 53!");
                msg.setVisible(true);
                correctFields = false;
            }
        }
        return correctFields;
    }
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Color green = new Color(102, 153, 0);
        msg.setVisible(false);
        msg.setForeground(Color.red);
        String strEN = empNumField.getText();
        String fN = fNField.getText();
        String lN = lNField.getText();
        String g = gField.getText();
        Object loc = locField.getSelectedItem();
        String strDeduc = deducField.getText();
        
        boolean correctFields = checkEmpInfo(true, strEN, fN, lN, g, strDeduc);
        
        if (fteButton.isSelected()) {  
            String strSalary = yearlyField.getText();
            
            correctFields = checkFTE(correctFields, strSalary);
            
            if (correctFields) {
                int eN = Integer.parseInt(strEN);
                double deduc = Double.parseDouble(strDeduc);
                double salary = Double.parseDouble(strSalary);
                FTE theFTE = new FTE(eN, fN, lN, g, 0, deduc, salary);
                
                theHT.addEmployee(theFTE);
                msg.setForeground(green);
                msg.setText("Full time employee added!");
                msg.setVisible(true);
                clearAddFields();
            }
            
        } else if (pteButton.isSelected()) {
            String strHourly = hourlyField.getText();
            String strHPW = hoursWeekField.getText();
            String strWPY = wYrField.getText();
        
            correctFields = checkPTE(correctFields, strHourly, strHPW, strWPY);
        
            if (correctFields) {
                int eN = Integer.parseInt(strEN);
                double deduc = Double.parseDouble(strDeduc);
                double hourly = Double.parseDouble(strHourly);
                double hPW = Double.parseDouble(strHPW);
                int wPY = Integer.parseInt(strWPY);
                PTE thePTE = new PTE(eN, fN, lN, g, 0, deduc, hourly, hPW, wPY);
                
                theHT.addEmployee(thePTE);
                msg.setForeground(green);
                msg.setText("Part time employee added!");
                msg.setVisible(true);
                clearAddFields();
            }            
        
        } else {
            msg.setText("Missing field. Please try again!");
            msg.setVisible(true);
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void fteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fteButtonActionPerformed
        if (fteButton.isSelected()) {
            ftePanel.setVisible(true);
            ptePanel.setVisible(false);
        }
    }//GEN-LAST:event_fteButtonActionPerformed

    private void pteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pteButtonActionPerformed
        if (pteButton.isSelected()) {
            ptePanel.setVisible(true);
            ftePanel.setVisible(false);
        }
    }//GEN-LAST:event_pteButtonActionPerformed

    private void addTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTabMousePressed
        msg.setVisible(false);
    }//GEN-LAST:event_addTabMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addTab;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField deducField;
    private javax.swing.JLabel deducText;
    private javax.swing.JPanel editTab;
    private javax.swing.JTextField empNumField;
    private javax.swing.JLabel empNumText;
    private javax.swing.JTextField fNField;
    private javax.swing.JLabel fNText;
    private javax.swing.JLabel fteArrow;
    private javax.swing.JRadioButton fteButton;
    private javax.swing.JPanel ftePanel;
    private javax.swing.JTextField gField;
    private javax.swing.JLabel gText;
    private javax.swing.JTextField hourlyField;
    private javax.swing.JLabel hourlyText;
    private javax.swing.JTextField hoursWeekField;
    private javax.swing.JLabel hrsWeekText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lNField;
    private javax.swing.JLabel lNText;
    private javax.swing.JComboBox<String> locField;
    private javax.swing.JLabel locText;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel pfpText;
    private javax.swing.JLabel pteArrow;
    private javax.swing.JRadioButton pteButton;
    private javax.swing.JPanel ptePanel;
    private javax.swing.JPanel removeTab;
    private javax.swing.JButton uploadButton;
    private javax.swing.JTextField wYrField;
    private javax.swing.JLabel wYrText;
    private javax.swing.JTextField yearlyField;
    private javax.swing.JLabel yearlyText;
    // End of variables declaration//GEN-END:variables
}
