
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jenna
 */

import java.awt.Color;
import java.util.ArrayList; 
import java.time.format.DateTimeFormatter;  
import java.time.LocalDateTime;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.ImageIcon;
import java.awt.Image;

public class EditJFrame extends javax.swing.JFrame {
    
    private MainJFrame mainFrame;
    private MyHashTable theHT;
    private ArrayList<String> locArray;
    final ImageIcon defaultPfp;
    private ImageIcon pfpAdd;
    private ImageIcon pfpEdit;

    /**
     * Creates new form EditJFrame
     */
    public EditJFrame() {
        initComponents();
        
        addMsg.setVisible(false);
        removeMsg.setVisible(false);
        removeButton.setEnabled(false);
        editMsg.setVisible(false);
        editButton.setEnabled(false);
    
        defaultPfp = new ImageIcon("C:\\Users\\jammy\\Documents\\NetBeansProjects\\JennasEMS\\src\\assets\\defaultPfp.png", "C:\\Users\\jammy\\Documents\\NetBeansProjects\\JennasEMS\\src\\assets\\defaultPfp.png");
        pfpAdd = defaultPfp;
        pfpAddLabel.setIcon(pfpAdd);
        
        pack();
    }
    
    //allows EditJFrame to use MainJFrame's updateTable method
    public void passMainFrame(MainJFrame mainFrame) {
        this.mainFrame = mainFrame;
    }
    
    //gets the hashtable from MainJFrame
    public void setHT(MyHashTable theHTRef) {
        theHT = theHTRef;
    }
    
    //gets the array of locations from MainJFrame
    public void setEditLocArray(ArrayList<String> locArrayRef) {
        locArray = locArrayRef;
        
        for (String loc : locArray){
            locAddField.addItem(loc);
        }
        for (String loc : locArray){
            locEditField.addItem(loc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButtonGroup = new javax.swing.ButtonGroup();
        editButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addTab = new javax.swing.JPanel();
        eNAddField = new javax.swing.JTextField();
        fNAddField = new javax.swing.JTextField();
        lNAddField = new javax.swing.JTextField();
        locAddField = new javax.swing.JComboBox<>();
        gAddField = new javax.swing.JTextField();
        deducAddField = new javax.swing.JTextField();
        pfpAddLabel = new javax.swing.JLabel();
        uploadAddButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        fNText = new javax.swing.JLabel();
        lNText = new javax.swing.JLabel();
        empNumText = new javax.swing.JLabel();
        locText = new javax.swing.JLabel();
        gText = new javax.swing.JLabel();
        deducText = new javax.swing.JLabel();
        pfpText = new javax.swing.JLabel();
        fteAddPanel = new javax.swing.JPanel();
        yrlyAddField = new javax.swing.JTextField();
        yearlyText = new javax.swing.JLabel();
        fteAddButton = new javax.swing.JRadioButton();
        pteAddPanel = new javax.swing.JPanel();
        hourlyText = new javax.swing.JLabel();
        hrsWeekText = new javax.swing.JLabel();
        wYrText = new javax.swing.JLabel();
        wYrAddField = new javax.swing.JTextField();
        hrlyAddField = new javax.swing.JTextField();
        hrsWAddField = new javax.swing.JTextField();
        pteAddButton = new javax.swing.JRadioButton();
        addMsg = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        fNEditField = new javax.swing.JTextField();
        lNEditField = new javax.swing.JTextField();
        gEditField = new javax.swing.JTextField();
        deducEditField = new javax.swing.JTextField();
        fteEditPanel = new javax.swing.JPanel();
        yrlyEditField = new javax.swing.JTextField();
        yearlyText2 = new javax.swing.JLabel();
        fteEditButton = new javax.swing.JRadioButton();
        pteEditPanel = new javax.swing.JPanel();
        hourlyText2 = new javax.swing.JLabel();
        hrsWeekText2 = new javax.swing.JLabel();
        wYrText2 = new javax.swing.JLabel();
        wYrEditField = new javax.swing.JTextField();
        hrlyEditField = new javax.swing.JTextField();
        hrsWEditField = new javax.swing.JTextField();
        pteEditButton = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        eNEditField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        editMsg = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        uploadEditButton = new javax.swing.JButton();
        locEditField = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        pfpEditLabel = new javax.swing.JLabel();
        searchEditButton = new javax.swing.JButton();
        searchEditField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        removeTab = new javax.swing.JPanel();
        searchRemoveField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        fNRemoveField = new javax.swing.JTextField();
        lNRemoveField = new javax.swing.JTextField();
        gRemoveField = new javax.swing.JTextField();
        deducRemoveField = new javax.swing.JTextField();
        locRemoveField = new javax.swing.JTextField();
        fteRemovePanel = new javax.swing.JPanel();
        yrlyRemoveField = new javax.swing.JTextField();
        yearlyText1 = new javax.swing.JLabel();
        pteRemovePanel = new javax.swing.JPanel();
        hourlyText1 = new javax.swing.JLabel();
        hrsWeekText1 = new javax.swing.JLabel();
        wYrText1 = new javax.swing.JLabel();
        wYrRemoveField = new javax.swing.JTextField();
        hrlyRemoveField = new javax.swing.JTextField();
        hrsWRemoveField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eNRemoveField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        removeMsg = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pfpRemoveLabel = new javax.swing.JLabel();
        searchRemoveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        addTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addTabMousePressed(evt);
            }
        });

        uploadAddButton.setText("UPLOAD");
        uploadAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadAddButtonActionPerformed(evt);
            }
        });

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        fNText.setText("First Name:");

        lNText.setText("Last Name:");

        empNumText.setText("Employee Number:");

        locText.setText("Location:");

        gText.setText("Gender:");

        deducText.setText("Deduction Rate:");

        pfpText.setText("Profile Picture:");

        yrlyAddField.setEditable(false);

        yearlyText.setText("Yearly Salary:");

        addButtonGroup.add(fteAddButton);
        fteAddButton.setText("Full Time  >");
        fteAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fteAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fteAddPanelLayout = new javax.swing.GroupLayout(fteAddPanel);
        fteAddPanel.setLayout(fteAddPanelLayout);
        fteAddPanelLayout.setHorizontalGroup(
            fteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteAddPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fteAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yearlyText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yrlyAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        fteAddPanelLayout.setVerticalGroup(
            fteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(yearlyText)
                .addComponent(yrlyAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fteAddButton))
        );

        hourlyText.setText("Hourly Wage:");

        hrsWeekText.setText("Hrs/W:");

        wYrText.setText("W/Yr:");

        wYrAddField.setEditable(false);

        hrlyAddField.setEditable(false);

        hrsWAddField.setEditable(false);

        addButtonGroup.add(pteAddButton);
        pteAddButton.setText("Part Time  >");
        pteAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pteAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pteAddPanelLayout = new javax.swing.GroupLayout(pteAddPanel);
        pteAddPanel.setLayout(pteAddPanelLayout);
        pteAddPanelLayout.setHorizontalGroup(
            pteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteAddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pteAddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hourlyText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrlyAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrsWeekText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrsWAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wYrText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wYrAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pteAddPanelLayout.setVerticalGroup(
            pteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteAddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hourlyText)
                .addComponent(hrlyAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hrsWeekText)
                .addComponent(hrsWAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(wYrText)
                .addComponent(wYrAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pteAddButton))
        );

        addMsg.setForeground(new java.awt.Color(255, 0, 0));
        addMsg.setText("______________________________________________________");
        addMsg.setToolTipText("");

        javax.swing.GroupLayout addTabLayout = new javax.swing.GroupLayout(addTab);
        addTab.setLayout(addTabLayout);
        addTabLayout.setHorizontalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fteAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addTabLayout.createSequentialGroup()
                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pfpAddLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createSequentialGroup()
                                    .addComponent(uploadAddButton)
                                    .addGap(15, 15, 15))
                                .addComponent(pfpText))
                            .addGap(43, 43, 43)
                            .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(addTabLayout.createSequentialGroup()
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gText)
                                        .addComponent(gAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(deducText)
                                        .addComponent(deducAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createSequentialGroup()
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fNText))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNText)
                                        .addComponent(lNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTabLayout.createSequentialGroup()
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(empNumText)
                                        .addComponent(eNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(locText)
                                        .addComponent(locAddField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(addTabLayout.createSequentialGroup()
                            .addComponent(addMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2))
                        .addComponent(pteAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        addTabLayout.setVerticalGroup(
            addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTabLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNText)
                    .addComponent(lNText)
                    .addComponent(pfpText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addComponent(pfpAddLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadAddButton))
                    .addGroup(addTabLayout.createSequentialGroup()
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empNumText)
                            .addComponent(locText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eNAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gText)
                            .addComponent(deducText))
                        .addGap(5, 5, 5)
                        .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deducAddField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addComponent(fteAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(pteAddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(addTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMsg)
                    .addComponent(addButton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD EMPLOYEE", addTab);

        jInternalFrame2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrame2.setVisible(true);

        fNEditField.setEditable(false);

        lNEditField.setEditable(false);

        gEditField.setEditable(false);

        deducEditField.setEditable(false);

        yrlyEditField.setEditable(false);

        yearlyText2.setText("Yearly Salary:");

        editButtonGroup.add(fteEditButton);
        fteEditButton.setText("Full Time  >");
        fteEditButton.setEnabled(false);
        fteEditButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fteEditButtonItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout fteEditPanelLayout = new javax.swing.GroupLayout(fteEditPanel);
        fteEditPanel.setLayout(fteEditPanelLayout);
        fteEditPanelLayout.setHorizontalGroup(
            fteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fteEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearlyText2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yrlyEditField, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
        );
        fteEditPanelLayout.setVerticalGroup(
            fteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(yearlyText2)
                .addComponent(yrlyEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(fteEditButton))
        );

        pteEditPanel.setFocusable(false);

        hourlyText2.setText("Hourly Wage:");

        hrsWeekText2.setText("Hrs/W:");

        wYrText2.setText("W/Yr:");

        wYrEditField.setEditable(false);

        hrlyEditField.setEditable(false);

        hrsWEditField.setEditable(false);

        editButtonGroup.add(pteEditButton);
        pteEditButton.setText("Part Time >");
        pteEditButton.setEnabled(false);
        pteEditButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pteEditButtonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pteEditPanelLayout = new javax.swing.GroupLayout(pteEditPanel);
        pteEditPanel.setLayout(pteEditPanelLayout);
        pteEditPanelLayout.setHorizontalGroup(
            pteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pteEditButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hourlyText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrlyEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrsWeekText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrsWEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wYrText2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wYrEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, Short.MAX_VALUE))
        );
        pteEditPanelLayout.setVerticalGroup(
            pteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hrlyEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hrsWeekText2)
                .addComponent(hrsWEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(wYrText2)
                .addComponent(wYrEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hourlyText2)
                .addComponent(pteEditButton))
        );

        jLabel8.setText("First Name:");

        jLabel9.setText("Last Name:");

        jLabel10.setText("Gender:");

        jLabel11.setText("Location:");

        jLabel12.setText("Deduction:");

        eNEditField.setEditable(false);
        eNEditField.setEnabled(false);

        jLabel13.setText("Employee #:");

        editMsg.setForeground(new java.awt.Color(255, 0, 0));
        editMsg.setText("________________________________________________");

        editButton.setText("MODIFY");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        uploadEditButton.setText("UPLOAD");
        uploadEditButton.setEnabled(false);
        uploadEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadEditButtonActionPerformed(evt);
            }
        });

        locEditField.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pfpEditLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pfpEditLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fteEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uploadEditButton)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(gEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(44, 44, 44)))
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(locEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(deducEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(eNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(pteEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(editMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadEditButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deducEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(locEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fteEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pteEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(editMsg))
                .addGap(16, 16, 16))
        );

        searchEditButton.setText("🔍");
        searchEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditButtonActionPerformed(evt);
            }
        });

        searchEditField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchEditFieldFocusGained(evt);
            }
        });

        jLabel14.setText("Search By Employee Number:");

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFrame2)
                    .addGroup(editTabLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchEditField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editTabLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEditButton)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MODIFY EMPLOYEE", editTab);

        searchRemoveField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchRemoveFieldFocusGained(evt);
            }
        });

        jLabel1.setText("Search By Employee Number:");

        jInternalFrame1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrame1.setVisible(true);

        fNRemoveField.setEditable(false);
        fNRemoveField.setFocusable(false);

        lNRemoveField.setEditable(false);
        lNRemoveField.setFocusable(false);

        gRemoveField.setEditable(false);
        gRemoveField.setFocusable(false);

        deducRemoveField.setEditable(false);
        deducRemoveField.setFocusable(false);

        locRemoveField.setEditable(false);
        locRemoveField.setFocusable(false);

        yrlyRemoveField.setEditable(false);
        yrlyRemoveField.setFocusable(false);

        yearlyText1.setText("Yearly Salary:");

        javax.swing.GroupLayout fteRemovePanelLayout = new javax.swing.GroupLayout(fteRemovePanel);
        fteRemovePanel.setLayout(fteRemovePanelLayout);
        fteRemovePanelLayout.setHorizontalGroup(
            fteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteRemovePanelLayout.createSequentialGroup()
                .addComponent(yearlyText1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yrlyRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fteRemovePanelLayout.setVerticalGroup(
            fteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(yearlyText1)
                .addComponent(yrlyRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hourlyText1.setText("Hourly Wage:");

        hrsWeekText1.setText("Hrs/W:");

        wYrText1.setText("W/Yr:");

        wYrRemoveField.setEditable(false);
        wYrRemoveField.setFocusable(false);

        hrlyRemoveField.setEditable(false);
        hrlyRemoveField.setFocusable(false);

        hrsWRemoveField.setEditable(false);
        hrsWRemoveField.setFocusable(false);

        javax.swing.GroupLayout pteRemovePanelLayout = new javax.swing.GroupLayout(pteRemovePanel);
        pteRemovePanel.setLayout(pteRemovePanelLayout);
        pteRemovePanelLayout.setHorizontalGroup(
            pteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteRemovePanelLayout.createSequentialGroup()
                .addComponent(hourlyText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrlyRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hrsWeekText1)
                .addGap(12, 12, 12)
                .addComponent(hrsWRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wYrText1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(wYrRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        pteRemovePanelLayout.setVerticalGroup(
            pteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pteRemovePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(hourlyText1)
                .addComponent(hrlyRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(hrsWeekText1)
                .addComponent(hrsWRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(wYrText1)
                .addComponent(wYrRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Gender:");

        jLabel6.setText("Location:");

        jLabel7.setText("Deduc:");

        eNRemoveField.setEditable(false);
        eNRemoveField.setFocusable(false);

        jLabel2.setText("Employee #:");

        removeMsg.setForeground(new java.awt.Color(255, 0, 0));
        removeMsg.setText("________________________________________________");

        removeButton.setText("REMOVE");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pfpRemoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pfpRemoveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(fteRemovePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(52, 52, 52))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(removeMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeButton))
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                                                    .addComponent(gRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addGap(44, 44, 44)))
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6)
                                                .addComponent(locRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(deducRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addComponent(eNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(pteRemovePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deducRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fteRemovePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pteRemovePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton)
                    .addComponent(removeMsg))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        searchRemoveButton.setText("🔍");
        searchRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeTabLayout = new javax.swing.GroupLayout(removeTab);
        removeTab.setLayout(removeTabLayout);
        removeTabLayout.setHorizontalGroup(
            removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeTabLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(removeTabLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(searchRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchRemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jInternalFrame1))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        removeTabLayout.setVerticalGroup(
            removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeTabLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(removeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchRemoveField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchRemoveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REMOVE EMPLOYEE", removeTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    private String getDate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");  
        LocalDateTime now = LocalDateTime.now();  
        return dtf.format(now);  
    }
    
    private ImageIcon uploadPfp(javax.swing.JLabel pfpLabel) {
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);
        
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            //file opened
            String file = fileChooser.getSelectedFile().getAbsolutePath();
            Image image = new ImageIcon(file).getImage().getScaledInstance(pfpLabel.getWidth(), pfpLabel.getHeight(), Image.SCALE_DEFAULT);
            ImageIcon pfp = new ImageIcon(image, file);
            pfpLabel.setIcon(pfp);
            return pfp;
        } else {
            //file chooser closed
            return null;
        }  
    }
    
    public void missingError(javax.swing.JLabel msg) {
        msg.setText("Missing field.");
        msg.setVisible(true);
    }
    
    private boolean checkEmpInfo(boolean editing, javax.swing.JLabel msg, String strEN, String fN, String lN, String g, int locIndex, String strDeduc) {
        if (strEN.isEmpty() || fN.isEmpty() || lN.isEmpty() || g.isEmpty() || locIndex<0 || strDeduc.isEmpty()) {
            missingError(msg);
            return false;
        } else {
            try {
                int eN = Integer.parseInt(strEN);
                if (eN < 1) {
                    msg.setText("Employee number must be a positive integer.");
                    msg.setVisible(true);
                    return false;
                } else if (theHT.searchEmployee(eN) != null && !editing){
                    msg.setText("Employee number is already in use.");
                    msg.setVisible(true);
                    return false;
                }
            } catch(Exception e) {
                msg.setText("Employee number must be a positive integer.");
                msg.setVisible(true);
                return false;
            }
            
            try {
                double deduc = Double.parseDouble(strDeduc);
                if (deduc > 1 || deduc < 0) {
                    msg.setText("Dedcution rate must be a decimal from 0 - 1.");
                    msg.setVisible(true);
                    return false;
                }             
            } catch (Exception e) {
                msg.setText("Dedcution rate must be a decimal from 0 - 1.");
                msg.setVisible(true);
                return false;
            }
            return true;
        }
    }
    
    private boolean checkFTE(javax.swing.JLabel msg, String strSalary) {
        if (strSalary.isEmpty()){
            missingError(msg);
            return false;
        } else {
            try {
                double salary = Double.parseDouble(strSalary);
                if (salary <= 0) {
                    msg.setText("Salary must be a positive integer.");
                    msg.setVisible(true);
                    return false;
                }
            } catch(Exception e) {
                msg.setText("Salary must be a positive integer.");
                msg.setVisible(true);
                return false;
            }
            return true;
        }
    }
    
    private boolean checkPTE(javax.swing.JLabel msg, String strHourly, String strHPW, String strWPY) {
        if (strHourly.isEmpty() || strHPW.isEmpty() || strWPY.isEmpty()){
            missingError(msg);
            return false;
        } else {
            try {
                double hourly = Double.parseDouble(strHourly);
                if (hourly <= 0) {
                    msg.setText("Hourly wage must be a positive integer.");
                    msg.setVisible(true);
                    return false;
                }
            } catch(Exception e) {
                msg.setText("Hourly wage must be a positive integer.");
                msg.setVisible(true);
                return false;
            }

            try {
                double hPW = Double.parseDouble(strHPW);
                if (hPW < 0 || hPW > 168) {
                    msg.setText("Hours/week must be between 0 and 168 hours.");
                    msg.setVisible(true);
                    return false;
                }
            } catch(Exception e) {
                msg.setText("Hours/week must be between 0 and 168 hours.");
                msg.setVisible(true);
                return false;
            }

            try {
                int wPY = Integer.parseInt(strWPY);
                if (wPY < 0 || wPY > 53) {
                    msg.setText("Weeks/year must be an integer between 0 and 53.");
                    msg.setVisible(true);
                    return false;
                }
            } catch(Exception e) {
                msg.setText("Weeks/year must be an integer between 0 and 53.");
                msg.setVisible(true);
                return false;
            }
            return true;
        }
    }
    
    private boolean displayEmployee(boolean editing, javax.swing.JTextField searchDisplay, javax.swing.JLabel msg, javax.swing.JLabel pfpDisplay, javax.swing.JTextField eNDisplay, javax.swing.JTextField fNDisplay, javax.swing.JTextField lNDisplay, javax.swing.JTextField genderDisplay, javax.swing.JTextField deducDisplay, javax.swing.JTextField yearlyDisplay, javax.swing.JTextField hourlyDisplay, javax.swing.JTextField hoursWeekDisplay, javax.swing.JTextField wYrDisplay) {
        String strENToFind = searchDisplay.getText();
        if (strENToFind.isEmpty()) {
            msg.setText("Input an employee number to search.");
            msg.setVisible(true);
            return false;
        } else {
            try {
                int eNToFind = Integer.parseInt(strENToFind);
            } catch(Exception e) {
                msg.setText("Employee number must be a positive integer.");
                msg.setVisible(true);
                return false;
            }
        }
        
        int eNToFind = Integer.parseInt(strENToFind);
        
        EmployeeInfo empFound = theHT.searchEmployee(eNToFind);
        if (empFound == null) {
            msg.setText("No employee found.");
            msg.setVisible (true);
            return false;
            
        } else {
            ImageIcon empPfp = empFound.pfp;
            Image imageFit = empPfp.getImage().getScaledInstance(pfpDisplay.getWidth(), pfpDisplay.getHeight(), Image.SCALE_DEFAULT);
            pfpDisplay.setIcon(new ImageIcon(imageFit, empPfp.getDescription()));
            
            eNDisplay.setText(Integer.toString(empFound.empNumber));
            fNDisplay.setText(empFound.firstName);
            lNDisplay.setText(empFound.lastName);
            genderDisplay.setText(empFound.gender);
            if (editing) {
                locEditField.setSelectedIndex(empFound.workLoc);
                pfpEdit = empPfp;
            } else {
                locRemoveField.setText(locArray.get(empFound.workLoc));
            }
            deducDisplay.setText(Double.toString(empFound.deductRate));
            
            if (empFound instanceof FTE fte) {
                yearlyDisplay.setText(Double.toString(fte.yearlySalary)); 
                if (editing) {
                    fteEditButton.setSelected(true);
                }
            } else if (empFound instanceof PTE pte) {
                hourlyDisplay.setText(Double.toString(pte.hourlyWage));
                hoursWeekDisplay.setText(Double.toString(pte.hoursPerWeek));
                wYrDisplay.setText(Integer.toString(pte.weeksPerYear));
                if (editing) {
                    pteEditButton.setSelected(true);
                }
            }
            return true;
        } 
    }
    
    private void clearFields(javax.swing.JTextField[] fieldsArray) {
        for (javax.swing.JTextField field : fieldsArray) {
            field.setText(null);
        }
    }
    
    private void clearUniqueAddFields() {
        locAddField.setSelectedIndex(0);
        addButtonGroup.clearSelection();
        pfpAdd = defaultPfp;
        pfpAddLabel.setIcon(defaultPfp);
    }
    
    private void clearUniqueEditFields() {
        locEditField.setSelectedIndex(0);
        editButtonGroup.clearSelection();
        pfpEditLabel.setIcon(null);
    }
    
    
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addMsg.setForeground(Color.red);
        
        javax.swing.JTextField[] addFieldsArray = {eNAddField, fNAddField, lNAddField, gAddField, deducAddField, yrlyAddField, hrlyAddField, hrsWAddField, wYrAddField};
        
        String strEN = eNAddField.getText(), fN = fNAddField.getText(), lN = lNAddField.getText(), g = gAddField.getText(), strDeduc = deducAddField.getText();
        int loc = locAddField.getSelectedIndex();
        String date = getDate();

        //checks regular fields
        boolean correctEmpFields = checkEmpInfo(false, addMsg, strEN, fN, lN, g, loc, strDeduc);
        
        if (correctEmpFields) {
            if (fteAddButton.isSelected()) {  
                String strSalary = yrlyAddField.getText();

                //checks fte specific fields
                boolean correctFTEFields = checkFTE(addMsg, strSalary);

                if (correctFTEFields) {
                    int eN = Integer.parseInt(strEN);
                    double deduc = Double.parseDouble(strDeduc), salary = Double.parseDouble(strSalary);

                    FTE theFTE = new FTE(date, pfpAdd, eN, fN, lN, g, loc, deduc, salary);
                    theHT.addEmployee(theFTE);
                    mainFrame.updateTable();

                    addMsg.setForeground(new Color(102, 153, 0));
                    addMsg.setText("Full time employee added!");
                    addMsg.setVisible(true);

                    clearFields(addFieldsArray);
                    clearUniqueAddFields();
                    yrlyAddField.setEditable(false);
                }

            } else if (pteAddButton.isSelected()) {
                String strHourly = hrlyAddField.getText(), strHPW = hrsWAddField.getText(), strWPY = wYrAddField.getText();

                //checks pte specific fields
                boolean correctPTEFields = checkPTE(addMsg, strHourly, strHPW, strWPY);

                if (correctPTEFields) {
                    int eN = Integer.parseInt(strEN), wPY = Integer.parseInt(strWPY);
                    double deduc = Double.parseDouble(strDeduc), hourly = Double.parseDouble(strHourly), hPW = Double.parseDouble(strHPW);

                    PTE thePTE = new PTE(date, pfpAdd, eN, fN, lN, g, loc, deduc, hourly, hPW, wPY);
                    theHT.addEmployee(thePTE);
                    mainFrame.updateTable();

                    addMsg.setForeground(new Color(102, 153, 0));
                    addMsg.setText("Part time employee added!");
                    addMsg.setVisible(true);

                    clearFields(addFieldsArray);
                    clearUniqueAddFields();
                    hrlyAddField.setEditable(false);
                    hrsWAddField.setEditable(false);
                    wYrAddField.setEditable(false);
                }            
            } else {
                missingError(addMsg);
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void fteAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fteAddButtonActionPerformed
        if (fteAddButton.isSelected()) {
            yrlyAddField.setEditable(true);
            hrlyAddField.setEditable(false);
            hrsWAddField.setEditable(false);
            wYrAddField.setEditable(false);
            hrlyAddField.setText(null);
            hrsWAddField.setText(null);
            wYrAddField.setText(null);
        }
    }//GEN-LAST:event_fteAddButtonActionPerformed

    private void pteAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pteAddButtonActionPerformed
        if (pteAddButton.isSelected()) {
            yrlyAddField.setEditable(false);
            yrlyAddField.setText(null);
            hrlyAddField.setEditable(true);
            hrsWAddField.setEditable(true);
            wYrAddField.setEditable(true);
        }
    }//GEN-LAST:event_pteAddButtonActionPerformed

    private void addTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTabMousePressed
        addMsg.setVisible(false);
    }//GEN-LAST:event_addTabMousePressed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        int eNToRemove = Integer.parseInt(eNRemoveField.getText());
        theHT.removeEmployee(eNToRemove);
        mainFrame.updateTable();
        
        removeMsg.setText("Employee " + eNToRemove + " removed!");
        removeMsg.setForeground(new Color(102, 153, 0)); 
        removeMsg.setVisible(true);
        
        javax.swing.JTextField[] removeFieldsArray = {searchRemoveField, eNRemoveField, fNRemoveField, lNRemoveField, gRemoveField, locRemoveField, deducRemoveField, yrlyRemoveField, hrlyRemoveField, hrsWRemoveField, wYrRemoveField};
        clearFields(removeFieldsArray);
        pfpRemoveLabel.setIcon(null);
        removeButton.setEnabled(false);
    }//GEN-LAST:event_removeButtonActionPerformed

    private void searchRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRemoveButtonActionPerformed
        removeMsg.setVisible(false);
        removeMsg.setForeground(Color.red);
        
        //regular fields will always be overrided by new data, but fte or pte fields may be empty and need to be cleared
        javax.swing.JTextField[] uncertainFields = {yrlyRemoveField, hrlyRemoveField, hrsWRemoveField, wYrRemoveField};
        clearFields(uncertainFields);
        
        boolean employeeDisplayed = displayEmployee(false, searchRemoveField, removeMsg, pfpRemoveLabel, eNRemoveField, fNRemoveField, lNRemoveField, gRemoveField, deducRemoveField, yrlyRemoveField, hrlyRemoveField, hrsWRemoveField, wYrRemoveField);
        if (employeeDisplayed) {
            removeButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchRemoveButtonActionPerformed

    private void searchRemoveFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchRemoveFieldFocusGained
        removeMsg.setVisible(false);
        removeMsg.setForeground(Color.red);
    }//GEN-LAST:event_searchRemoveFieldFocusGained

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        javax.swing.JTextField[] editFieldsArray = {eNEditField, fNEditField, lNEditField, gEditField, deducEditField, yrlyEditField, hrlyEditField, hrsWEditField, wYrEditField};
        
        int eNToEdit = Integer.parseInt(eNEditField.getText());
        EmployeeInfo empToEdit = theHT.searchEmployee(eNToEdit);
        
        //preserves original date
        String empDate = empToEdit.date;
        
        String strEN = eNEditField.getText(), fN = fNEditField.getText(), lN = lNEditField.getText(), g = gEditField.getText(), strDeduc = deducEditField.getText();
        int loc = locEditField.getSelectedIndex();
        
        //checks regular fields
        boolean correctEmpFields = checkEmpInfo(true, editMsg, strEN, fN, lN, g, loc, strDeduc);
        
        if (correctEmpFields) {
            if (fteEditButton.isSelected()) {  
                String strSalary = yrlyEditField.getText();

                //checks fte specific fields
                boolean correctFTEFields = checkFTE(editMsg, strSalary);

                if (correctFTEFields) {
                    double deduc = Double.parseDouble(strDeduc), salary = Double.parseDouble(strSalary);

                    theHT.removeEmployee(eNToEdit);
                    FTE theFTE = new FTE(empDate, pfpEdit, eNToEdit, fN, lN, g, loc, deduc, salary);
                    theHT.addEmployee(theFTE);
                    mainFrame.updateTable();

                    editMsg.setText("Employee " + eNToEdit + " edited!");
                    editMsg.setForeground(new Color(102, 153, 0)); 
                    editMsg.setVisible(true);

                    clearFields(editFieldsArray);
                    clearUniqueEditFields();

                    editButton.setEnabled(false);
                    uploadEditButton.setEnabled(false);
                    for (javax.swing.JTextField field : editFieldsArray) {
                        field.setEditable(false);
                    }
                    locEditField.setEnabled(false);
                    fteEditButton.setEnabled(false);
                    pteEditButton.setEnabled(false);
                }

            } else if (pteEditButton.isSelected()) {
                String strHourly = hrlyEditField.getText(), strHPW = hrsWEditField.getText(), strWPY = wYrEditField.getText();

                //checks pte specific fields
                boolean correctPTEFields = checkPTE(editMsg, strHourly, strHPW, strWPY);

                if (correctPTEFields) {
                    int wPY = Integer.parseInt(strWPY);
                    double deduc = Double.parseDouble(strDeduc), hourly = Double.parseDouble(strHourly), hPW = Double.parseDouble(strHPW);

                    theHT.removeEmployee(eNToEdit);
                    PTE thePTE = new PTE(empDate, pfpEdit, eNToEdit, fN, lN, g, loc, deduc, hourly, hPW, wPY);
                    theHT.addEmployee(thePTE);
                    mainFrame.updateTable();

                    editMsg.setText("Employee " + eNToEdit + " edited!");
                    editMsg.setForeground(new Color(102, 153, 0)); 
                    editMsg.setVisible(true);

                    clearFields(editFieldsArray);
                    clearUniqueEditFields();

                    editButton.setEnabled(false);
                    uploadEditButton.setEnabled(false);
                    for (javax.swing.JTextField field : editFieldsArray) {
                        field.setEditable(false);
                    }
                    locEditField.setEnabled(false);
                    fteEditButton.setEnabled(false);
                    pteEditButton.setEnabled(false);
                }            

            } else {
                missingError(editMsg);
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditButtonActionPerformed
        editMsg.setVisible(false);
        editMsg.setForeground(Color.red);
        
        boolean employeeDisplayed = displayEmployee(true, searchEditField, editMsg, pfpEditLabel, eNEditField, fNEditField, lNEditField, gEditField, deducEditField, yrlyEditField, hrlyEditField, hrsWEditField, wYrEditField);
        if (employeeDisplayed) {
            editButton.setEnabled(true);
            uploadEditButton.setEnabled(true);
            javax.swing.JTextField[] editableFields = {fNEditField, lNEditField, gEditField, deducEditField};
            for (javax.swing.JTextField field : editableFields) {
                field.setEditable(true);
            }
            locEditField.setEnabled(true);
            fteEditButton.setEnabled(true);
            pteEditButton.setEnabled(true);
        }
    }//GEN-LAST:event_searchEditButtonActionPerformed

    private void searchEditFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchEditFieldFocusGained
        editMsg.setVisible(false);
        editMsg.setForeground(Color.red);
    }//GEN-LAST:event_searchEditFieldFocusGained

    private void pteEditButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pteEditButtonStateChanged
        if (pteEditButton.isSelected()) {
            yrlyEditField.setEditable(false);
            yrlyEditField.setText(null);
            hrlyEditField.setEditable(true);
            hrsWEditField.setEditable(true);
            wYrEditField.setEditable(true);
        }
    }//GEN-LAST:event_pteEditButtonStateChanged

    private void uploadAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadAddButtonActionPerformed
        ImageIcon pfpVar = uploadPfp(pfpAddLabel);
        if (pfpVar != null) {
            pfpAdd = pfpVar;
        }
    }//GEN-LAST:event_uploadAddButtonActionPerformed

    private void uploadEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadEditButtonActionPerformed
        ImageIcon pfpVar = uploadPfp(pfpEditLabel);
        if (pfpVar != null) {
            pfpEdit = pfpVar;
        }
    }//GEN-LAST:event_uploadEditButtonActionPerformed

    private void fteEditButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fteEditButtonItemStateChanged
        if (fteEditButton.isSelected()) {
            yrlyEditField.setEditable(true);
            hrlyEditField.setEditable(false);
            hrsWEditField.setEditable(false);
            wYrEditField.setEditable(false);
            hrlyEditField.setText(null);
            hrsWEditField.setText(null);
            wYrEditField.setText(null);
        }
    }//GEN-LAST:event_fteEditButtonItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.ButtonGroup addButtonGroup;
    private javax.swing.JLabel addMsg;
    private javax.swing.JPanel addTab;
    private javax.swing.JTextField deducAddField;
    private javax.swing.JTextField deducEditField;
    private javax.swing.JTextField deducRemoveField;
    private javax.swing.JLabel deducText;
    private javax.swing.JTextField eNAddField;
    private javax.swing.JTextField eNEditField;
    private javax.swing.JTextField eNRemoveField;
    private javax.swing.JButton editButton;
    private javax.swing.ButtonGroup editButtonGroup;
    private javax.swing.JLabel editMsg;
    private javax.swing.JPanel editTab;
    private javax.swing.JLabel empNumText;
    private javax.swing.JTextField fNAddField;
    private javax.swing.JTextField fNEditField;
    private javax.swing.JTextField fNRemoveField;
    private javax.swing.JLabel fNText;
    private javax.swing.JRadioButton fteAddButton;
    private javax.swing.JPanel fteAddPanel;
    private javax.swing.JRadioButton fteEditButton;
    private javax.swing.JPanel fteEditPanel;
    private javax.swing.JPanel fteRemovePanel;
    private javax.swing.JTextField gAddField;
    private javax.swing.JTextField gEditField;
    private javax.swing.JTextField gRemoveField;
    private javax.swing.JLabel gText;
    private javax.swing.JLabel hourlyText;
    private javax.swing.JLabel hourlyText1;
    private javax.swing.JLabel hourlyText2;
    private javax.swing.JTextField hrlyAddField;
    private javax.swing.JTextField hrlyEditField;
    private javax.swing.JTextField hrlyRemoveField;
    private javax.swing.JTextField hrsWAddField;
    private javax.swing.JTextField hrsWEditField;
    private javax.swing.JTextField hrsWRemoveField;
    private javax.swing.JLabel hrsWeekText;
    private javax.swing.JLabel hrsWeekText1;
    private javax.swing.JLabel hrsWeekText2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lNAddField;
    private javax.swing.JTextField lNEditField;
    private javax.swing.JTextField lNRemoveField;
    private javax.swing.JLabel lNText;
    private javax.swing.JComboBox<String> locAddField;
    private javax.swing.JComboBox<String> locEditField;
    private javax.swing.JTextField locRemoveField;
    private javax.swing.JLabel locText;
    private javax.swing.JLabel pfpAddLabel;
    private javax.swing.JLabel pfpEditLabel;
    private javax.swing.JLabel pfpRemoveLabel;
    private javax.swing.JLabel pfpText;
    private javax.swing.JRadioButton pteAddButton;
    private javax.swing.JPanel pteAddPanel;
    private javax.swing.JRadioButton pteEditButton;
    private javax.swing.JPanel pteEditPanel;
    private javax.swing.JPanel pteRemovePanel;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel removeMsg;
    private javax.swing.JPanel removeTab;
    private javax.swing.JButton searchEditButton;
    private javax.swing.JTextField searchEditField;
    private javax.swing.JButton searchRemoveButton;
    private javax.swing.JTextField searchRemoveField;
    private javax.swing.JButton uploadAddButton;
    private javax.swing.JButton uploadEditButton;
    private javax.swing.JTextField wYrAddField;
    private javax.swing.JTextField wYrEditField;
    private javax.swing.JTextField wYrRemoveField;
    private javax.swing.JLabel wYrText;
    private javax.swing.JLabel wYrText1;
    private javax.swing.JLabel wYrText2;
    private javax.swing.JLabel yearlyText;
    private javax.swing.JLabel yearlyText1;
    private javax.swing.JLabel yearlyText2;
    private javax.swing.JTextField yrlyAddField;
    private javax.swing.JTextField yrlyEditField;
    private javax.swing.JTextField yrlyRemoveField;
    // End of variables declaration//GEN-END:variables
}
